// Minimal flat ESLint config — generated by Pass 2 sweep.
// Repo: dev-tracker (Vue + TypeScript)
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: {
        // Node globals
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        // Browser globals (Vue client)
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        HTMLElement: 'readonly',
      },
    },
  },
  {
    rules: {
      // Express middleware/error handlers legitimately declare unused params
      // (`_next` etc.) — Express identifies error handlers by arity 4.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    ignores: ['dist/**', 'node_modules/**', 'client/dist/**'],
  },
];
