services:
  dev-tracker-server:
    image: ghcr.io/xoje-tech/dev-tracker-server:latest
    network_mode: host
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped

  caddy:
    image: docker.io/library/caddy:2-alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - dev-tracker-server
